import React from "react";
import {useNavigate as navigate } from "react-router-dom";
import { Formik, Field, Form } from "formik";

function AddPayment() {
  const handleSubmit = values => {
    const requestPayments = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response = await fetch("http://localhost:3001/api/v1/payments", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ data: values })
      });
      if (response.status === 201) {
        navigate("/");
      }
    };
    requestPayments();
  };

  return (
    <div>
      <h2>Add your Payment</h2>
      <Formik
        initialValues={{
          type: "payments",
          attributes: {
            amount: "",
            date: "",
            account_id: "",
            user_id: ""
          }
        }}
        onSubmit={handleSubmit}
      >{() => (
        <Form>
          <Field type="text" name="attributes.amount" />
          <Field type="text" name="attributes.date" />
          <Field type="text" name="attributes.account_id" />
          <Field type="text" name="attributes.user_id" />

          <button type="submit">Create</button>
        </Form>
      )}</Formik>
    </div>
  );
}

export default AddPayment;